### ISSUE TITLE
Oauth setup

### ISSUE THREAD

**Issue by gschrader** [kholloway/smartthings-dsc-alarm#1]
Thanks for putting this together, the oauth gear is causing me grief though.

I get all the way to the test url and I'm getting this:

```
{
error: true,
type: "AccessDenied",
message: "This request is not authorized by the specified access token"
}
```

Any ideas?

**Comment by gschrader** [comment]
Oh I also had issues with not being able to select the Alarm Panel in the smart app, I had to just change the pretence as so:

```
        input "panel", "capability.switch", title: "Choose Alarm Panel?", multiple: false, required: true
```

I'm not sure why device.dSCPanel doesn't work for me.

**Comment by kholloway** [comment]
So the device name (and capability names I think) has to match your device type name in Camel Case (which IMHO is annoying and error prone).

So my device type name is exactly "DSC Panel" so it's camel case name needs to be "device.dSCPanel". If your device type for the panel is something else you need to adjust it accordingly.

You always lowercase the first letter then upper case each resulting letter after a space.
So even if my device name was 'DSC panel' in the input section it would be 'device.dSCPanel' to signify a space between the two words.

**Comment by kholloway** [comment]
I screwed up those API docs, you need to replace the oauth_client_id bit with the appID not the Oauth ID. I will update the doc in a minute to reflect that issue.

So to get your AppID go to https://graph.api.smartthings.com/api/smartapps/installations/ and search for a "label" matching your application and copy down it's id: field in the json output.
Use that id field in place of my incorrectly named oauth_client_id field in just the test URL bits.

**Comment by gschrader** [comment]
Mine is also "DSC Panel", I'll play around with different names to see if it will pick it up.

Ah ok I will try the AppID.  Thanks!

**Comment by kholloway** [comment]
Ok I updated that doc with the proper info, that should make things work properly.
To be honest I had lots of problems with authorizing the device(s) each time I did it.
It was very hit or miss and sometimes for hours on end you just couldn't authorize anything at all.

One thing that also bit me a few times was I had a space at the end of my device type name in the input line like this "device.dSCPanel " and it took me hours to see it, nothing would authorize until I removed the space so just double check that whole input line and make sure there are no extra spaces in any of the quoted values.

**Comment by kholloway** [comment]
And "DSC Panel" is your device type name right? Not your actual device name?
So in the "My Device Types" that should be it's name and in "My Devices" it should be named something else like "Alarm Panel".

Also double check if you copy/pasted that there is no extra spaces or odd characters in the device type name. Might be worth it to highlight the entire thing and replace it with hand typed text IF you copy/pasted originally and then make sure you "save" and then "publish -> for me" before trying again.

**Comment by gschrader** [comment]
Ok that is working better now, I get the panelstatus tile getting updated but not the zone tiles.  I can toggle them by hitting the url directly though so I'm not sure where the disconnect is.  I'll see if I can trace it through.

**Comment by kholloway** [comment]
The "standardTile" definitions in the device type code need to match your zone numbers. So if you have a zone open event from zone1 you need to have a matching tile "zone1", "device.zone1" in the "DSC Alarm" device type code. If you already have that then I'm not sure what the issue is but you can remove some of the comment lines in the device type to increase the log data that is returned and you can see those messages in the logs tab on the dev site.

**Comment by kholloway** [comment]
One other idea, for the zone(s) you are testing do they have a custom name in the 'alarmserver.cfg' file? If they don't you won't get any notification for them as I'm currently ignoring devices without custom names.

So for zone1 alarmserver.cfg has to have a matching 'zone1=Whatever' for it to send notices at all.

**Comment by gschrader** [comment]
Yes I've named my zones and I've matched them to the tiles, right now I've only hooked up 1-4 to test.  Here's a log snippet:

```
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:51 PM MDT: debug Command: 650
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:51 PM MDT: debug Zone/Partition: 1
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:51 PM MDT: debug Panel: [Alarm Panel]
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:50 PM MDT: debug Command: 610
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:50 PM MDT: debug Zone/Partition: 3
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:50 PM MDT: debug Panel: [Alarm Panel]
a1fbb2f4-eaa6-449e-9e98-023e2b071e91 5:26:50 PM MDT: debug In Closed function for Zone: 3
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:44 PM MDT: debug Command: 651
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:44 PM MDT: debug Zone/Partition: 1
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:44 PM MDT: debug Panel: [Alarm Panel]
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:44 PM MDT: debug Command: 609
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:44 PM MDT: debug Zone/Partition: 3
1cf740a8-d6a8-43e7-9811-fedde68b49ad 5:26:44 PM MDT: debug Panel: [Alarm Panel]
a1fbb2f4-eaa6-449e-9e98-023e2b071e91 5:26:44 PM MDT: debug In Open function for Zone: 3
```

So I've opened up my zone 3 and the events are coming in, I even get into the methods in the panel groovy code so I think things are mapped right, so I'm thinking it must be what's getting passed to sendEvent that is wrong.  In this example should it be 3, zone3 or device.zone3?

**Comment by kholloway** [comment]
It should be "zone3" getting passed to the sendEvent function and "partition1" for partitions.

I found the error and fixed it in the AlarmServer code, go grab my change and restart your alarmserver.py and events should start working properly. 

Sorry about that but thanks for setting all this up so I could have someone else testing with me! :)

**Comment by kholloway** [comment]
Hopefully it's working for you but I can't test my change since my setup is fully broken now due to the current "can't save" bug in the IDE. Hopefully they fix it soon, I wanted to get a bunch of changes put in place today and I have not been able to use it all day.

**Comment by gschrader** [comment]
Yup that did the trick, thanks for your help!

Yeah the web IDE is a major pita, it's the reason I haven't hacked on it very much.

**Comment by Broadscope** [comment]
I'm having the same problem that @gschrader mentioned at the top. 

{
error: true,
type: "AccessDenied",
message: "This request is not authorized by the specified access token"
}

What should I do? AlarmServer is working perfectly, but SmartThings not so much.

**Comment by kholloway** [comment]
@Broadscope So walk me through the steps you took to get it setup...

Also one of the main issues I have seen is that people forget to authorize the individual zones after everything is setup. You do that via the Smartthings iOS or Android app in the Smartapps section/config for the app you installed. Make sure you select all the zones and the panel device you created so the app can talk to them.

If that's not the issue walk through the REST API setup guide again slowly making sure you don't miss anything. I wish there was a better/more automated way to set this all up but there just isn't. It's cumbersome and error prone and took me a long time to even get my example code working because of the oAuth crap.

**Comment by Broadscope** [comment]
@kholloway I followed your steps here: https://github.com/kholloway/smartthings-dsc-alarm/blob/master/RESTAPISetup.md

There is only one access_token right? For the app. 

{
  "access_token": "acXXXXXXXf9-dXXXXXf-XX32-aXXXX7-feX9XXXXX73c",
  "expires_in": 1576799999,
  "scope": "app",
  "token_type": "bearer"
}

**Comment by kholloway** [comment]
@Broadscope Yes that is the access_token field you need to copy down after doing the Second URL part of my setup guide and it looks correct also (even though you blanked out portions of it, the format is correct).

**Comment by Broadscope** [comment]
Do I need to set something up on my android smartthings app in a certain way? Should I be uninstalling/reinstalling my DSC SmartThings App each time my access code changes?

**Comment by kholloway** [comment]
No you don't need to do anything on your smartphone, the only other thing I can think that would be wrong is you have the wrong appID for your app?

**Comment by Broadscope** [comment]
YOU ARE CORRECT! I wasn't using a JSON formatter so I copied the second ID
in the list, not the ID above the "label" line. Such a dumb mistake!!!
Works fine now!

Do we have arm/disarm functionality yet?

**Comment by kholloway** [comment]
Glad to hear you got it working!
I don't have arm/disarm yet on purpose.

I'm not willing to expose my alarm web interface to the internet directly so my other choices for control of the system via Smartthings would be HTTPS via a local hub action (not currently supported, only HTTP is supported), my other alternative which I'm still considering is using a SparkCore device to expose that same functionality but with all the security already built into the SparkCore platform. Basically the Core becomes a middle-man device. I have also considered using a Raspberry Pi with a Z-Wave module as the middle-man.

**Comment by Sastozki** [comment]
@kholloway
Hey Kent,
Any thoughts on this? 

Something I recently noticed, on Smartthings the Panel icon works in real-time, however the zones, are functioning a bit differently. They will only update if another zone is triggered.

For example, when i open my front door (zone 2) the icon will show open and remain open, if I close the door, not matter how long I wait, it will now update until another zone is triggered. So if I then open my back door, zone 2 will show closed (if closed) and then the my back door will remain open until another zone is triggered.

The EV3 and python scripts are showing the correct states of the zones however the data is not getting to Smartthings.

I am using the latest rev of the code with the changes that @MattTW made a few days ago so I am not sure something in the updates might have changed this.

Have you seen this issue? Is there something that we can update in the SmartApp that can poll or refresh the data its getting from the script?
