### ISSUE TITLE
Icons won't update

### ISSUE THREAD

**Issue by kholloway** [kholloway/smartthings-dsc-alarm#4]
@Sastozki lets chat here about your icons not updating..

**Comment by Sastozki** [comment]
@kholloway here is the output with the debugging. 

265b0967-842e-4c28-828e-782bf645d0cc 10:13:23 PM: debug paneldevices: Panel - partition1 is ready
265b0967-842e-4c28-828e-782bf645d0cc 10:13:23 PM: debug It was a zone... ready
265b0967-842e-4c28-828e-782bf645d0cc 10:13:23 PM: debug Zone or partition: partition1
265b0967-842e-4c28-828e-782bf645d0cc 10:13:23 PM: debug Options after lookup: [partition, ready]
265b0967-842e-4c28-828e-782bf645d0cc 10:13:21 PM: debug paneldevices: Panel - partition1 is notready
265b0967-842e-4c28-828e-782bf645d0cc 10:13:21 PM: debug It was a zone... notready
265b0967-842e-4c28-828e-782bf645d0cc 10:13:21 PM: debug Zone or partition: partition1
265b0967-842e-4c28-828e-782bf645d0cc 10:13:21 PM: debug Options after lookup: [partition, notready]

**Comment by kholloway** [comment]
Ok so that's all the output from your partition statuses (and looks good), what does the stuff for a zone show up as?

Remember for the Ademco/Vista panel you will see zone opens instantly but the closes will take up to 5 minutes because that panel doesn't advertise the close events.

**Comment by kholloway** [comment]
Also I'm assuming your panel/partition device networkID is 'partition1' right?

**Comment by Sastozki** [comment]
Correct, I have partition1 as my network ID for my panel.  The panel and zones are all showing under my devices as  inactive.   And they all must have a value of on as things show armed, open or motion. 

Panel   paneldevices    Home    Ohio Ave    As      partition1  INACTIVE    7 hours ago
BST_Windows zonedevices Home    Ohio Ave    As      zone6   INACTIVE    

![capture](https://cloud.githubusercontent.com/assets/5542406/3451232/a859a50e-0190-11e4-9995-ab962fe38563.JPG)

**Comment by kholloway** [comment]
can you grab a screenshot of your devices from the smartthings IDE?
You don't have to include everything just a few of the zone devices would be great.

**Comment by Sastozki** [comment]
![all](https://cloud.githubusercontent.com/assets/5542406/3451257/4fd195e4-0191-11e4-8bee-ab55de15b8d8.JPG)
![panel](https://cloud.githubusercontent.com/assets/5542406/3451256/4fd08e7e-0191-11e4-9ba5-aa75391f88b6.JPG)
![zone](https://cloud.githubusercontent.com/assets/5542406/3451258/4fd651a6-0191-11e4-8984-70af1b3bd5be.JPG)

**Comment by kholloway** [comment]
Your zone2 has a space between the word zone and the number.
The rest of the devices look good.

The Device types are 'zonedevices', if you copy/pasted the code from here:
https://github.com/kholloway/smartthings-dsc-alarm/blob/master/devicetypes/DSCZoneContact.groovy

then the device type would be "DSC Zone Contact" or "DSC Zone" not "zonedevices"..

**Comment by Sastozki** [comment]
I changed everything back to the way it should be and still not getting anything.

**Comment by Sastozki** [comment]
I was looking over the code for the device types, did I have to add a line for each "zone" or does the code parse out each zone that is labeled by its number? 

/*
-  DSC Zone Device
  *
-  Author: Matt Martz matt.martz@gmail.com
-  Date: 2014-04-28
  */

// for the UI
metadata {
  definition (name: "DSC Zone", author: "matt.martz@gmail.com") {
    // Change or define capabilities here as needed
    capability "Refresh"
    capability "Contact Sensor"
    capability "Polling"
    capability "Sensor"

```
// Add commands as needed
command "zone"
```

  }

  simulator {
    // Nothing here, you could put some testing stuff here if you like
  }

  tiles {
    // Main Row
    standardTile("zone", "device.contact", width: 2, height: 2, canChangeBackground: true, canChangeIcon: true) {
      state "open",   label: '${name}', icon: "st.contact.contact.open",   backgroundColor: "#ffa81e"
      state "closed", label: '${name}', icon: "st.contact.contact.closed", backgroundColor: "#79b821"
      state "alarm",  label: '${name}', icon: "st.contact.contact.open",   backgroundColor: "#ff0000"
    }

```
// This tile will be the tile that is displayed on the Hub page.
main "zone"

// These tiles will be displayed when clicked on the device, in the order listed here.
details(["zone"])
```

  }
}

// handle commands
def zone(String state) {
  // state will be a valid state for a zone (open, closed)
  // zone will be a number for the zone
  log.debug "Zone: ${state}"
  sendEvent (name: "contact", value: "${state}")
}

def poll() {
  log.debug "Executing 'poll'"
  // TODO: handle 'poll' command
  // On poll what should we do? nothing for now..
}

def refresh() {
  log.debug "Executing 'refresh' which is actually poll()"
  poll()
  // TODO: handle 'refresh' command
}

**Comment by Sastozki** [comment]
Here is some more out put from the zone:

265b0967-842e-4c28-828e-782bf645d0cc 10:44:18 AM: debug paneldevices: Panel - partition1 is ready
265b0967-842e-4c28-828e-782bf645d0cc 10:44:18 AM: debug It was a zone... ready
265b0967-842e-4c28-828e-782bf645d0cc 10:44:18 AM: debug Zone or partition: partition1
265b0967-842e-4c28-828e-782bf645d0cc 10:44:18 AM: debug Options after lookup: [partition, ready]
265b0967-842e-4c28-828e-782bf645d0cc 10:44:16 AM: debug zonedevices.deviceNetworkId are [zone2, zone5, zone3, zone6, zone19, zone20, zone18, zone4, zone17]
265b0967-842e-4c28-828e-782bf645d0cc 10:44:16 AM: debug zonedevices.displayName are [Front_Door, Kitchen_Windows, LR_Windows, BST_Windows, FR_Windows, Foyer_Motion, FR_Door, DR_Windows, Garage_Door]
265b0967-842e-4c28-828e-782bf645d0cc 10:44:16 AM: debug zonedevices.id are [04267222-6734-4747-8aec-f220b7b9c353, 0dcf5290-7366-45c5-befe-4fe877046ad0, 312bc247-bbae-4566-85b5-0e70d5d859ed, 773ae82a-4bad-4fec-9e77-36471a785bba, 7ecd1ea2-5732-4025-829e-d7d1e0a4867a, 978c68d9-5abb-41d1-8807-ad8d06f84b9e, d5e44414-c665-4fa8-829d-1cc78ba38e3c, da198969-ed73-446a-8f07-e230d80bc983, fb3a82ef-f936-4753-9abe-b159c7ae99f2]
265b0967-842e-4c28-828e-782bf645d0cc 10:44:16 AM: debug zonedevices: [Front_Door, Kitchen_Windows, LR_Windows, BST_Windows, FR_Windows, Foyer_Motion, FR_Door, DR_Windows, Garage_Door] - zone20 is closed

**Comment by Sastozki** [comment]
Update:
Using the test URL you provided in your RESTAPISETUP, I was able to get the icons to change based on the codes. That said, when I run the alarmserver, the events are getting triggered, passing the data to ST, but the devices are not getting updated, nor are they being recognized as part of the smartapp.   

Here is some of the IDE output when i used the test URL...
on Ohio Ave via sendHubCommand
79df84db-4e3c-4700-90da-0e47ede6b174 4:14:59 PM: debug DSC%20ZoneContact
79df84db-4e3c-4700-90da-0e47ede6b174 4:14:59 PM: debug Was True... Zone Device: DSC ZoneContact at zone2 is closed
79df84db-4e3c-4700-90da-0e47ede6b174 4:14:59 PM: debug zonedevices: [DSC ZoneContact, DSC ZoneContact, DSC ZoneContact, DSC ZoneContact, DSC ZoneContact, DSC ZoneMotion, DSC ZoneContact, DSC ZoneContact, DSC ZoneContact] - 2 is closed
79df84db-4e3c-4700-90da-0e47ede6b174 4:12:08 PM: debug paneldevices: DSC Panel - partition1 is ready
79df84db-4e3c-4700-90da-0e47ede6b174 4:12:05 PM: debug paneldevices: DSC Panel - partition1 is notready
79df84db-4e3c-4700-90da-0e47ede6b174 4:11:22 PM: debug Executing GET /jsonrpc?request={"jsonrpc":"2.0","method":"GUI.ShowNotification","params":{"title":"DSC%20ZoneMotion","message":"closed"},"id":1} HTTP/1.1
HOST: null:null

on Ohio Ave via sendHubCommand
79df84db-4e3c-4700-90da-0e47ede6b174 4:11:22 PM: debug DSC%20ZoneMotion
79df84db-4e3c-4700-90da-0e47ede6b174 4:11:22 PM: debug Was True... Zone Device: DSC ZoneMotion at zone20 is closed
79df84db-4e3c-4700-90da-0e47ede6b174 4:11:22 PM: debug zonedevices: [DSC ZoneContact, DSC ZoneContact, DSC ZoneContact, DSC ZoneContact, DSC ZoneContact, DSC ZoneMotion, DSC ZoneContact, DSC ZoneContact, DSC ZoneContact] - 20 is closed
79df84db-4e3c-4700-90da-0e47ede6b174 4:10:52 PM: debug Executing GET /jsonrpc?request={"jsonrpc":"2.0","method":"GUI.ShowNotification","params":{"title":"DSC%20ZoneMotion","message":"open"},"id":1} HTTP/1.1
HOST: null:null

**Comment by kholloway** [comment]
Ok so if the test URL works but the stuff coming from honeyalarmserver doesn't work that means something is not configured right in the SmartthingsPlugin in the honeyalarmserver.

**Comment by Sastozki** [comment]
I figured it out....

The URL that were being created were putting the words,  "partition and zone"  into the URL and it was sending that information to Smartthings.  

The test URL does not have these words into.so i removed it and then it worked.

**Comment by kholloway** [comment]
So was that something I need to fix in my code or something that was somewhere else?

**Comment by kholloway** [comment]
Thanks for the info by the way, I figured out that the smart app code in github doesn't expect the words 'zone' or 'partition' as you found out the hard way but both the AlarmServer and the HoneyAlarmServer code had those words being sent. I have updated the smartthings branch of AlarmServer and my fork of the HoneyAlarmServer to fix that issue.

Thanks again and sorry for the hassle!

**Comment by Sastozki** [comment]
@kholloway @MattTW

I understand that the Ademco/Vista panel will see zone opens instantly but the closes will take up to 5 minutes because that panel doesn't advertise the close events.  However, if the EV3 shows that the zone is closed should Smartthing's be seeing the same thing?   

When I look at the logs on the EV3 and the HoneyAlarmServer, the zones are showing closed, however smartthings shows them open still open and does for a while.  Does this have something to do with the poll and refresh within the smartthings plug in?

**Comment by MattTW** [comment]
re: 1st Question:  Each zone event reported by the Envisalink TPI is passed to HoneyAlarmServer plugins immediately to process (keep in mind the name config stuff I mentioned earlier, tho), and the SmartThings plugin is hitting a URL each time that happens.

However,  I have observed is that even taking into account the current TPI doc saying it can take up to a minute for a zone to report as closed,  those events consistently do not come across from Envisalink, at least in my setup.    There is a separate "dump zone timers" that is periodically called that asks Envisalink to return the "last closed" status of each zone...Not sure if you are referring to those...by default I make a call to dump these every 60 seconds -  my observation has been that these timers are generally in the ballpark but not necessarily exact either and definitely get "tripped" when no corresponding zone close event has been sent.

So it kinda depends on what you are looking at in the HoneyAlarmServer logs.   If you want to post log snippets or send me your full logs, we can see for sure.   I do feel there are bugs in the Envisalink Ademco TPI zone event handling, I need to gather up supporting info and send it along to them.   Having info from more than more system will help strengthen the argument that it isn't working correctly.

**Comment by kholloway** [comment]
So when all the zones close the panel goes back to "READY" state right (that's how my DSC panel works anyway).
Maybe we could track which zones are open and send close events for them OR just send close events for all zones when the panel goes into "READY" state as a way to make them close sooner?

**Comment by Sastozki** [comment]
I am seeing it a lot more with the motion sensors.  My panel is working the same way, its going to ready but the zone is still showing open.

**Comment by MattTW** [comment]
Yep, I was thinking along the same lines as a workaround.   It still probably wouldn't be 100% accurate (I haven't thought through all possible use cases) - but it would be way more accurate than it is now.

**Comment by Sastozki** [comment]
@kholloway 
Hey  Kent,  
Something I recently noticed, on Smartthings the Panel icon works in real-time, however the zones, are functioning a bit differently.  They will only update if another zone is triggered.  

For example, when i open my front door (zone 2) the icon will show open and remain open, if I close the door, not matter how long I wait, it will now update until another zone is triggered.  So if I then open my back door, zone 2 will show closed (if closed) and then the my back door will remain open until another zone is triggered.   

The EV3 and python scripts are showing the correct states of the zones however the data is not getting to Smartthings.   

I am using the latest rev of the code with the changes that @MattTW made a few days ago so I am not sure something in the updates might have changed this.    

Have you seen this issue?  Is there something that we can update in the  SmartApp that can poll or refresh the data its getting from the script?

**Comment by kholloway** [comment]
@Sastozki looks like the recent update to @MattTW HoneyAlarm server project by @lgleasain may resolve the issue you are seeing. It adds more frequent updates for the zones, see the link below if you are interested in what changed by either way you should update the HoneyAlarm code you have and see if that fixes the problems you have been seeing.

https://github.com/MattTW/HoneyAlarmServer/pull/4

Let me know if that fixes the issue for you or not.
Thanks!

**Comment by kholloway** [comment]
@Sastozki also just FYI I'm not seeing the problems with zones updating on my setup using the original AlarmServer code so I'm not sure if it's an issue with the HoneyAlarm Server, the Smartthings code or something else.
