### ISSUE TITLE
Cannot run alarmserver.py

### ISSUE THREAD

**Issue by blazenelams** [kholloway/smartthings-dsc-alarm#9]
When i try to run alarmserver.py, I get the following response from command line. 
![image](https://user-images.githubusercontent.com/11069699/27307547-d0e649ac-550f-11e7-8e83-35020c10b897.png)

Any advice would help, I have been tring to get this to work for a while now.

**Comment by kholloway** [comment]
Looks like you might be running Python3 which I'm not sure works properly with this project.

**Comment by blazenelams** [comment]
Ya, thats the issue, i had to change alot of sintax in the code to work with Python 3.
Thanks for the quick feedback.
